Spaces link modals
Availity/availity-react pull request #1116
Opened 2022-07-01 17:53 UTC by stevenviar

I'll add more tests for the modals, but wanted to get this out there and see if anyone has any concerns/feedback. This is based on an older alpha version of Spaces currently used by one of our apps which needs the modal functionality. 

**Before submitting a pull request,** please make sure the following is done:

1. Fork [the repository](https://github.com/availity/availity-react) and create your branch from `master`.
2. Run `yarn` in the repository root.
3. If you've fixed a bug or added code that should be tested, add tests!
4. Ensure the test suite passes (`yarn test`). Tip: `yarn test --watch TestName` is helpful in development.
5. Make sure your code passed the conventional commits check. Read more about [conventional commits](https://www.conventionalcommits.org/en/v1.0.0-beta.4/#summary)

2022-07-01 18:04 UTC, jordan-a-young requested changes

2022-07-01 18:04 UTC, jordan-a-young commented on packages/spaces/src/modals/DisclaimerModal.js
> +  const fetchDisclaimer = async () => {
I think we should change the `useEffectAsync` to `useEffect` and move this function inside of there

2022-07-05 14:38 UTC, LauRoxx commented on packages/spaces/src/modals/ModalProvider.js
> +        <ModalHeader>{title}</ModalHeader>
The reactstrap modal needs a little more to be compliant. Example code snippet I pulled from the Dialog Structure story on the ADA Board:
`<Modal
   labelledBy="feedback-form-header"
   role="dialog"
   aria-modal>`
    `<ModalHeader
        id="feedback-form-header">`

2022-07-05 15:02 UTC, LauRoxx commented on packages/spaces/src/modals/ModalProvider.js
> +        <ModalHeader>{title}</ModalHeader>
forgot that reactstrap modalheader is an h5 which is not correct for modals. reactstrap lets you change the modal-title tag but classnames are passed to the outer div. This is the workaround that was done for feedback to keep the h5 styling.

`<ModalHeader id="feedback-form-header"
        role="heading"
        aria-level="2"
        className="h5"
        tag="div">`

or you could probably also do 
`<ModalHeader tag="div"><h2 className="h5">{title}</h2></ModalHeader>`

2022-07-05 21:05 UTC, stevenviar commented on packages/spaces/src/modals/ModalProvider.js
> +        <ModalHeader>{title}</ModalHeader>
Thanks for the examples, updated and think everything should be resolved now.

2022-07-11 16:10 UTC, jordan-a-young approved these changes

2022-07-12 18:34 UTC, gregmartDOTin approved these changes

2022-07-12 19:15 UTC, merged