feat(training-link): make training link 508 compliant by adding opens…
Availity/availity-react pull request #1120
Opened 2022-07-11 16:43 UTC by availityVolpe

… in a new tab to the demo link, change test to match new verbiage

**Before submitting a pull request,** please make sure the following is done:

1. Fork [the repository](https://github.com/availity/availity-react) and create your branch from `master`.
2. Run `yarn` in the repository root.
3. If you've fixed a bug or added code that should be tested, add tests!
4. Ensure the test suite passes (`yarn test`). Tip: `yarn test --watch TestName` is helpful in development.
5. Make sure your code passed the conventional commits check. Read more about [conventional commits](https://www.conventionalcommits.org/en/v1.0.0-beta.4/#summary)

2022-07-11 17:11 UTC, availityVolpe commented
Blocking resolution of 508 compliance for appeals Dashboard component 
https://jira.availity.com/browse/APPL-2694

2022-07-11 17:49 UTC, LauRoxx requested changes

2022-07-11 17:49 UTC, LauRoxx commented on packages/training-link/src/TrainingLink.tsx
> +    <span className="sr-only">(opens in a new tab) </span>
this should be within the link https://amp.levelaccess.net/public/standards/view_best_practice.php?violation_id=398

2022-07-13 12:16 UTC, LauRoxx approved these changes

2022-07-13 12:16 UTC, merged