Add support for spaces query status parameter
Availity/availity-react pull request #1138
Opened 2022-08-10 15:31 UTC by gogo-jscott

**Before submitting a pull request,** please make sure the following is done:

1. Fork [the repository](https://github.com/availity/availity-react) and create your branch from `master`.
2. Run `yarn` in the repository root.
3. If you've fixed a bug or added code that should be tested, add tests!
4. Ensure the test suite passes (`yarn test`). Tip: `yarn test --watch TestName` is helpful in development.
5. Make sure your code passed the conventional commits check. Read more about [conventional commits](https://www.conventionalcommits.org/en/v1.0.0-beta.4/#summary)

2022-08-10 16:41 UTC, jordan-a-young commented on packages/page-header/src/PageHeader.js
> +  variables: PropTypes.object,
Can you add this to the PageHeaderProps type as well please? The type should be `Record<string, unknown>`

2022-08-10 16:42 UTC, jordan-a-young requested changes
I think it looks good other than the missing type def.

@chrishavekost @owolfhu1 @gregmartDOTin Will updating the default query have any negative impact on the spaces api?

2022-08-10 16:43 UTC, jordan-a-young commented on packages/page-header/src/PageHeader.js
> +  variables: PropTypes.object,
Also, what do you think about naming the prop `spacesVariables`? That way it will be less generic

2022-08-11 15:50 UTC, chrishavekost commented
I think @owolfhu1 is looking into how this will affect the API but I'm wondering if @gogo-jscott can explain the reasoning behind these changes and if they're needed for everyone. If it's a one-off change I think each component will let you override the default query

2022-08-11 16:01 UTC, dnoler commented
@chrishavekost I can provide context for this change. We source payer spaces for payer logos, but we have an issue on Claims where a particular payer has an inactive payer space, so their logo isn't found. Granted, we probably should have a better solution for how we source payer logos, but this gets us to where we can at least define inactive spaces for payers that don't have a proper payer space section on the portal.

2022-08-11 16:20 UTC, owolfhu1 commented
Can confirm updated query is still be working

2022-08-11 18:05 UTC, gogo-jscott commented
Closing since feature goes outside intended purpose of package.

2022-08-11 18:05 UTC, closed without merging