Feat/training link props
Availity/availity-react pull request #1198
Opened 2022-12-07 19:28 UTC by urmilanalla

**Before submitting a pull request,** please make sure the following is done:

1. Fork [the repository](https://github.com/availity/availity-react) and create your branch from `master`.
2. Run `yarn` in the repository root.
3. If you've fixed a bug or added code that should be tested, add tests!
4. Ensure the test suite passes (`yarn test`). Tip: `yarn test --watch TestName` is helpful in development.
5. Make sure your code passed the conventional commits check. Read more about [conventional commits](https://www.conventionalcommits.org/en/v1.0.0-beta.4/#summary)

2022-12-07 19:34 UTC, jordan-a-young requested changes

2022-12-07 19:34 UTC, jordan-a-young commented on README.md
> +
Do you mind removing this new line please?

2022-12-07 19:34 UTC, jordan-a-young commented on packages/training-link/src/TrainingLink.stories.tsx
> +import { ArgsTable } from '@storybook/addon-docs';
This import should come before the `TrainingLink` import. We can move it to line 3.

2022-12-08 13:28 UTC, closed without merging

2022-12-08 13:29 UTC, urmilanalla commented
Duplicate PR