Add tooltip with escape controls
Availity/availity-react pull request #1227
Opened 2023-01-17 18:24 UTC by Valar05

Add accessible tooltip using reactstrap tooltip with escape to close and sectable text.

2023-01-17 18:58 UTC, jordan-a-young requested changes

2023-01-17 18:58 UTC, jordan-a-young commented on packages/tooltip/package.json
> +  "version": "2.1.2",
Can you change this to 1.0.0 please?

2023-01-17 18:58 UTC, jordan-a-young commented on packages/tooltip/package.json
> +  "author": "Kyle Gray <kyle.gray@availity.com>",
You can change this to your own info or mine if you don't want to put your own

2023-01-17 18:58 UTC, jordan-a-young commented on packages/tooltip/package.json
> +    "@availity/icon": "workspace:*",
We should be able to remove this dependency as well as @availity/message-core

2023-01-18 14:26 UTC, LauRoxx commented on packages/help/tsconfig.json
> +  "include": [".", "src/Tooltip.stories.tsx"],
looks like this is leftover from when we were going to put it in the help package

2023-01-18 14:26 UTC, LauRoxx commented on packages/tooltip/package.json
> +    "react": ">=16.3.0"
add reactstrap here

2023-01-24 14:18 UTC, jordan-a-young approved these changes

2023-01-24 17:57 UTC, merged