feat(typography): converting to typescript (#1282)
Availity/availity-react pull request #1283
Opened 2023-05-29 21:31 UTC by clintonlunn

closes #1282 

**Before submitting a pull request,** please make sure the following is done:

1. Fork [the repository](https://github.com/availity/availity-react) and create your branch from `master`.
2. Run `yarn` in the repository root.
3. If you've fixed a bug or added code that should be tested, add tests!
4. Ensure the test suite passes (`yarn test`). Tip: `yarn test --watch TestName` is helpful in development.
5. Make sure your code passed the conventional commits check. Read more about [conventional commits](https://www.conventionalcommits.org/en/v1.0.0-beta.4/#summary)

2023-06-04 22:32 UTC, nylon22 submitted a review, later dismissed

2023-06-06 18:56 UTC, clintonlunn commented
I changed some of the stories to hopefully be more accurate now. I thought the lorem ipsum filler text took away from the readability of the storybook page so i shortened it.

2023-06-23 19:01 UTC, jordan-a-young approved these changes

2023-06-23 19:01 UTC, jordan-a-young commented on packages/typography/src/Agreement.tsx
> +  tag?: ElementType | string;
`ElementType` should suffice here. I believe it includes the strings we need so we don't have to specify the `string` type

2023-06-23 19:01 UTC, jordan-a-young commented on packages/typography/stories/typography.stories.tsx
> +  children: <p>Sample agreement text</p>,
I think for this control we should only allow text and move the `<p />` to inside the story already. That way people using the controls only have to worry about the text and not the html tags

2023-06-23 19:01 UTC, jordan-a-young commented on packages/typography/stories/typography.stories.tsx
> +  children: <p>Sample disclaimer text</p>,
Same comment from the agreement args.

2023-06-23 19:01 UTC, jordan-a-young commented on packages/typography/tests/Agreement.test.tsx
> +  afterEach(cleanup);
You can remove this cleanup line. The latest version of `@testing-library/react` does this for us

2023-06-23 19:01 UTC, jordan-a-young commented on packages/typography/tests/Disclaimer.test.tsx
> +  afterEach(cleanup);
Same thing

2023-06-23 19:02 UTC, jordan-a-young requested changes
Misclick. Meant to hit request changes.

2023-06-27 14:27 UTC, jordan-a-young approved these changes

2023-06-27 14:30 UTC, merged