feat(link): default rel prop when linking to external sites
Availity/availity-react pull request #410
Opened 2019-12-20 21:11 UTC by chrishavekost

Provides `rel` with default value of `noopener noreferrer` when linking to external sites. Based on best practice detailed [here](https://developers.google.com/web/tools/lighthouse/audits/noopener).

This will only apply if `target = "_blank"`, `rel` has no specified value, the URL is `absolute`, `loadApp = false`, and the destination hostname is not the same as our current hostname.

`AvLink` has also been modified so that `getUrl` is only called once, and the `absolute` property of the `href` has been extracted for reuse.

2019-12-20 21:17 UTC, GoPro16 commented on packages/link/Link.js
> +  if ((target = '_blank') && !rel && absolute) {
Just wanted to make sure this is correct here. So the only time the first condition would fail is if `target === null`

2019-12-20 21:18 UTC, GoPro16 reviewed
Tests look good, just want to confirm that is the only edge case we need to account for above.

2019-12-20 21:23 UTC, nylon22 requested changes

2019-12-20 21:23 UTC, nylon22 commented on packages/link/Link.js
> +  if ((target = '_blank') && !rel && absolute) {
https://eslint.org/docs/rules/no-cond-assign has this to say:

> There are valid reasons to use assignment operators in conditional statements.

I think we should be explicitly checking if `target` is equal to `"_blank"`
```
if (target === '_blank' && ...

2019-12-20 21:23 UTC, nylon22 commented on packages/link/Link.js
> +  rel,
rather than destructuring `rel` from props, leave it out, and if it's specified it will be spread onto the `Tag` and override whatever we set it to.

2019-12-21 02:04 UTC, nylon22 approved these changes
LGTM

2019-12-23 13:49 UTC, merged