Feat/phone
Availity/availity-react pull request #442
Opened 2020-02-07 21:00 UTC by chrishavekost

This PR adds a standard phone component for teams to use in their forms. The reason for it being placed in its own package is so that the bundle size of `@availity/yup` and `@availity/form` doesn't grow unnecessarily larger due to `libphonenumber-js`.

`libphonenumber-js` was chosen because it is heavily based on Google's phone number library, but comes in a smaller package.

The `Phone` component works with `yup.phone()` validation OOTB, and a new `validatePhone()` `yup` method has been written. It uses a relaxed validation by default ([benefits](https://github.com/catamphetamine/libphonenumber-js/blob/master/README.md#using-phone-number-validation-feature)), and strict validation can be used with `yup.string().validatePhone(errorMessage, true)`.

To aid in 508 compliance and a [better user experience](https://www.filamentgroup.com/lab/politespace.html), phone numbers (and partial numbers) are only formatted `onBlur`.

Along the way, while trying to resolve issues with `Jest` and unit tests, many packages across `availity-react` were updated. I believe I resolved the few breaking changes introduced.

2020-02-07 21:26 UTC, GoPro16 requested changes
A little scary that this package is quite large just for phone validation but should be okay if we are not using everything provided. Would be interesting to see a bundle size on our apps when its included and minified.

2020-02-07 21:26 UTC, GoPro16 commented on packages/phone/typings/Phone.d.ts
> +export interface PhoneProps extends Field {
`PhoneProps` should be extending [FieldProps](https://github.com/Availity/availity-react/blob/master/packages/form/typings/Field.d.ts#L6) not field.

2020-02-07 21:26 UTC, GoPro16 commented on storybook/stories/phone.stories.js
> +storiesOf('TODO|Phone', module)
You should still put this under `Form` in storybook.

2020-02-07 21:26 UTC, GoPro16 commented on docs/source/form/phone/index.mdx
> +title: Phone
This still needs to be added to `gatsby-config.js`?

2020-02-07 21:33 UTC, chrishavekost commented
> A little scary that this package is quite large just for phone validation but should be okay if we are not using everything provided. Would be interesting to see a bundle size on our apps when its included and minified.

I agree, that's one reason I think it should be a separate package. You just reminded me though, I want to include an example in the doc of how to lazy load this with dynamic imports and `Suspense`, so that the larger size has less of an impact.

2020-02-11 19:14 UTC, GoPro16 approved these changes
LGTM

2020-02-11 19:14 UTC, merged