chore(feedback): upgrade native-form to v4
Availity/availity-react pull request #835
Opened 2021-10-08 17:53 UTC by jordan-a-young

I upgraded the `@availity/native-form` to version 4. Added an `await` since the function is now `async`

2021-10-18 12:39 UTC, chrishavekost requested changes

2021-10-18 12:39 UTC, chrishavekost commented on packages/feedback/src/SupportForm.js
> +    await nativeForm(ssoId, attributes, { action: href, target: '_blank' });
Since the salesforce SSO is always `saml`, we can send that string as the `type` variable to [avoid another api call in nativeForm](https://github.com/Availity/sdk-js/blob/29164d0e5aedfe8714fefc56692bfaa57b9acad4/packages/native-form/src/index.js?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L20-L31)

2021-10-19 13:56 UTC, jordan-a-young commented on packages/feedback/src/SupportForm.js
> +    await nativeForm(ssoId, attributes, { action: href, target: '_blank' });
Done

2021-10-28 19:41 UTC, chrishavekost submitted a review, later dismissed

2021-10-28 20:01 UTC, merged